#include <stdio.h>
#define _____________________ unsigned
#define ____________________________ do
#define _______________ double
#define _________________________________ goto
#define __________________________________ return
#define ________________________________ register
#define __ continue
#define bbbbbb 0
#define _________________________ while
#define ________________________ if
#define _______ sizeof
#define ___________________ short
#define ______________________________ case
#define ______________ int
#define _______________________ const
#define bbb 20
#define ____________________ signed
#define ____________________________________ getch
#define _ auto
#define __________ switch
#define __________________ char
#define _____ typedef
#define _______________________________ enum
#define ___________ void
#define ________ default
#define ___ extern
#define ___________________________ else
#define _________ struct
#define ____ volatile
#define __________________________ for
#define _____________ scanf
#define ______ union
#define ______________________ static
#define ________________ float
#define _________________ long
#define ____________ printf
#define _____________________________ break
#define ___________________________________ main
______________ ___________________________________(){__________________ aaa[bbb];____________("\x59\x6f\x75\x72\x20\x6e\x61\x6d\x65\x3a\x20");_____________("\x25\x73", aaa);____________("\x48\x65\x6c\x6c\x6f\x2c\x20\x25\x73\x21", aaa);____________________________________();__________________________________ bbbbbb;}
