#include <stdio.h>
#define _________________ long
#define ____________________________________ getch
#define _____________________ unsigned
#define ____________ printf
#define bbbbbbbbbbbbbbbbbb 0
#define ______________________ static
#define _____________ scanf
#define __________________ char
#define ____________________ signed
#define ___ extern
#define ____________________________ do
#define ________ default
#define ________________________________ register
#define _________________________ while
#define bbbbbbbbbbbbbbb 10
#define ___________________________ else
#define ______ union
#define bbbbbbbbb 45
#define ___________________ short
#define _______ sizeof
#define _______________ double
#define __________________________________ return
#define _ auto
#define ______________________________ case
#define __________________________ for
#define _________ struct
#define bbb 9808
#define _________________________________ goto
#define _____________________________ break
#define ___________ void
#define ________________________ if
#define bbbbbbbbbbbbbbbbbbbbb 1
#define ________________ float
#define ______________ int
#define _______________________ const
#define __ continue
#define _____ typedef
#define _______________________________ enum
#define bbbbbb 324
#define ___________________________________ main
#define ____ volatile
#define bbbbbbbbbbbb 90
#define __________ switch
______________ aaa(______________ aaaaaa[], ______________ aaaaaaaaaaaaaaa){______________ aaaaaaaaaaaa;______________ aaaaaaaaa = aaaaaa[bbbbbbbbbbbbbbbbbb];__________________________ (aaaaaaaaaaaa = bbbbbbbbbbbbbbbbbbbbb; aaaaaaaaaaaa < aaaaaaaaaaaaaaa; aaaaaaaaaaaa++)________________________ (aaaaaa[aaaaaaaaaaaa] > aaaaaaaaa)aaaaaaaaa = aaaaaa[aaaaaaaaaaaa];__________________________________ aaaaaaaaa;}______________ ___________________________________(){______________ aaaaaa[] = {bbbbbbbbbbbbbbb, bbbbbb, bbbbbbbbb, bbbbbbbbbbbb, bbb};______________ aaaaaaaaaaaaaaa = _______(aaaaaa)/_______(aaaaaa[bbbbbbbbbbbbbbbbbb]);____________("\x4c\x61\x72\x67\x65\x73\x74\x20\x69\x6e\x20\x67\x69\x76\x65\x6e\x20\x61\x72\x72\x61\x79\x20\x69\x73\x20\x25\x64", aaa(aaaaaa, aaaaaaaaaaaaaaa));__________________________________ bbbbbbbbbbbbbbbbbb;}
