#include <stdio.h>
#define ___________________________ else
#define __________________________________ return
#define ______________ int
#define _______________________________ enum
#define ____ volatile
#define bbbbbb 100
#define ______ union
#define ____________ printf
#define bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb 5
#define bbbbbbbbbbbbbbbbbbbbb 10
#define ____________________________ do
#define bbbbbbbbbbbb 93
#define _____________ scanf
#define ___ extern
#define ________________ float
#define ____________________ signed
#define _________________ long
#define __________________________ for
#define _________ struct
#define __________ switch
#define bbbbbbbbbbbbbbbbbbbbbbbbbbb 1
#define bbbbbbbbbbbbbbbbbb 20
#define __________________ char
#define ___________________________________ main
#define ___________________ short
#define bbb 2000
#define ____________________________________ getch
#define ________________________ if
#define ___________ void
#define ________________________________ register
#define _________________________ while
#define _____________________ unsigned
#define _____________________________ break
#define ______________________________ case
#define _______________ double
#define bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb 2
#define _________________________________ goto
#define _______ sizeof
#define ________ default
#define _____ typedef
#define bbbbbbbbb 200
#define ______________________ static
#define _ auto
#define bbbbbbbbbbbbbbb 50
#define bbbbbbbbbbbbbbbbbbbbbbbb 0
#define __ continue
#define bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb 9
#define _______________________ const
#define COINS bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
#define MAX bbbbbbbbbbbbbbbbbb
______________ aaaaaaaaa[COINS] = { bbbbbbbbbbbbbbbbbbbbbbbbbbb, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, bbbbbbbbbbbbbbbbbbbbb, bbbbbbbbbbbbbbbbbb,bbbbbbbbbbbbbbb, bbbbbb, bbbbbbbbb, bbb };___________ aaaaaa(______________ aaaaaaaaaaaa){______________ aaa[MAX] = { bbbbbbbbbbbbbbbbbbbbbbbb };______________ aaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaa = bbbbbbbbbbbbbbbbbbbbbbbb;__________________________ (aaaaaaaaaaaaaaa = COINS - bbbbbbbbbbbbbbbbbbbbbbbbbbb; aaaaaaaaaaaaaaa >= bbbbbbbbbbbbbbbbbbbbbbbb; aaaaaaaaaaaaaaa--) {_________________________ (aaaaaaaaaaaa >= aaaaaaaaa[aaaaaaaaaaaaaaa]) {aaaaaaaaaaaa -= aaaaaaaaa[aaaaaaaaaaaaaaa];aaa[aaaaaaaaaaaaaaaaaa++] = aaaaaaaaa[aaaaaaaaaaaaaaa];}}__________________________ (aaaaaaaaaaaaaaa = bbbbbbbbbbbbbbbbbbbbbbbb; aaaaaaaaaaaaaaa < aaaaaaaaaaaaaaaaaa; aaaaaaaaaaaaaaa++) {____________("\x25\x64\x20", aaa[aaaaaaaaaaaaaaa]);}__________________________________;}______________ ___________________________________(___________){______________ aaaaaaaaaaaaaaaaaaaaa = bbbbbbbbbbbb;____________("\x46\x6f\x6c\x6c\x6f\x77\x69\x6e\x67\x20\x69\x73\x20\x6d\x69\x6e\x69\x6d\x61\x6c\x20\x6e\x75\x6d\x62\x65\x72""\x6f\x66\x20\x63\x68\x61\x6e\x67\x65\x20\x66\x6f\x72\x20\x25\x64\x3a\x20",aaaaaaaaaaaaaaaaaaaaa);aaaaaa(aaaaaaaaaaaaaaaaaaaaa);__________________________________ bbbbbbbbbbbbbbbbbbbbbbbb;}
